# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitglance < Formula
  desc "Simple git terminal UI."
  homepage "https:github.com/michaelhass/gitglance"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michaelhass/gitglance/releases/download/v0.9.0/gitglance_Darwin_x86_64.tar.gz"
      sha256 "7b16d824de50910c8e4b25de665047ce284df5e6cbded98c3a2c2d48c95d1e42"

      def install
        bin.install "gitglance"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michaelhass/gitglance/releases/download/v0.9.0/gitglance_Darwin_arm64.tar.gz"
      sha256 "ab9e97211eb35ca081f1ba6ad76dbbae4f35fdb815714dcb6a3571750d8495cf"

      def install
        bin.install "gitglance"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/michaelhass/gitglance/releases/download/v0.9.0/gitglance_Linux_x86_64.tar.gz"
      sha256 "d0d8d79710be8eab5c8dc896719896133ac38922244dd20cee4dc392c1f187f6"
      def install
        bin.install "gitglance"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michaelhass/gitglance/releases/download/v0.9.0/gitglance_Linux_arm64.tar.gz"
      sha256 "79224bcc28639aab2d801f83dba03d9f46a918677daed94c37851cc8d5120198"
      def install
        bin.install "gitglance"
      end
    end
  end
end
