# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitglance < Formula
  desc "Simple git terminal UI."
  homepage "https:github.com/michaelhass/gitglance"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michaelhass/gitglance/releases/download/v0.5.0/gitglance_Darwin_x86_64.tar.gz"
      sha256 "8f15590bad5736a29a1fa7b847af04e29aab167ba60d51ef57148dd00f613d0b"

      def install
        bin.install "gitglance"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michaelhass/gitglance/releases/download/v0.5.0/gitglance_Darwin_arm64.tar.gz"
      sha256 "74d2e4093d943ba24aba4e327a183461620ae01d53742e27bb369629c06dc49d"

      def install
        bin.install "gitglance"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/michaelhass/gitglance/releases/download/v0.5.0/gitglance_Linux_x86_64.tar.gz"
      sha256 "8895b59989e313d1e4ee1e1c9600381fa6dce02f53ec51f9006b0529aae97570"
      def install
        bin.install "gitglance"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michaelhass/gitglance/releases/download/v0.5.0/gitglance_Linux_arm64.tar.gz"
      sha256 "509a6d4eead260a612f700dd4b5f80458b9eaab0fe1b604d6174e66f44f0613f"
      def install
        bin.install "gitglance"
      end
    end
  end
end
